apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: study-notion
  labels:
    role: backend
    env: demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: backend
  template:
    metadata:
      labels:
        role: backend
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: backend
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
          requests:
            cpu: "0.5"
            memory: "200Mi"
        envFrom:
        - secretRef:
            name: backend-sec
        image: 339713132076.dkr.ecr.ap-south-1.amazonaws.com/study-notion-backend:latest
        imagePullPolicy: Always
        env:
          - name: MONGO_CONN_STR
            value: mongodb+srv://mongodb-svc@cluster0.gdxackk.mongodb.net/StudyNotion?directConnection=true
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: password
        ports:
        - containerPort: 8080
