apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: study-notion
  labels:
    app: backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
          requests:
            cpu: "0.5"
            memory: "200Mi"
        image: amit2210/study-notion:backend
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
