apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: study-notion
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 90
      targetPort: 4000
  type: LoadBalancer
