apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: study-notion
  labels:
    app: frontend
spec:
  containers:
    - name: frontend
      image: amit2210/study-notion:frontend
      resources:
        limits:
          cpu: "1"
          memory: "500Mi"
        requests:
          cpu: "0.5"
          memory: "200Mi"
      imagePullPolicy: Always
      ports:
        - containerPort: 3000