apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: study-notion
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30009
  type: NodePort
