name: React CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v2
      with:
        ref: main

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Install Dependencies
      run: npm install

    - name: Install Vite
      run: npm install vite

    - name: Run ESLint
      run: npm run format

    - name: Run Tests
      run: npm run test

    - name: Build
      run: npm run build